vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        cards:
            uri_prefix: /images/cards
            upload_destination: '%kernel.project_dir%/public/images/cards'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        extensions:
            uri_prefix: /images/extensions
            upload_destination: '%kernel.project_dir%/public/images/extensions'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        masks:
            uri_prefix: /images/masks
            upload_destination: '%kernel.project_dir%/public/images/masks'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        foils:
            uri_prefix: /images/foils
            upload_destination: '%kernel.project_dir%/public/images/foils'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
