services:
    php:
        image: barlito/youl-tcg:${TAG}
        volumes:
            - ytcg_caddy_data:/data
        environment:
            SERVER_NAME: "ytcg.barlito.fr"
            DATABASE_URL: "postgresql://${DB_USER}:${DB_PASSWORD}@ytcg_db:5432/ytcg?serverVersion=13&charset=utf8"
            JWT_PUBLIC_KEY: "${JWT_PUBLIC_KEY}"
            JWT_SECRET_KEY: "${JWT_SECRET_KEY}"
            JWT_PASSPHRASE: "${JWT_PASSPHRASE}"
        logging:
            driver: loki
            options:
                loki-url: "http://176.31.100.99:3100/loki/api/v1/push"
        tty: true
        deploy:
            labels:
                - traefik.enable=true

                - traefik.http.services.ytcg.loadbalancer.server.port=80

                - traefik.http.routers.ytcg.rule=Host(`ytcg.barlito.fr`)
                - traefik.http.routers.ytcg.entrypoints=http
                - traefik.http.routers.ytcg.middlewares=tls-redirectscheme

                - traefik.tcp.routers.ytcg-secure.rule=HostSNI(`ytcg.barlito.fr`)
                - traefik.tcp.routers.ytcg-secure.entrypoints=https
                - traefik.tcp.routers.ytcg-secure.tls=true
                - traefik.tcp.routers.ytcg-secure.tls.passthrough=true
                - traefik.tcp.services.ytcg-secure.loadbalancer.server.port=443
        networks:
            - traefik_traefik_proxy
            - ytcg_internal

    db:
        image: postgres:13
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ytcg
        volumes:
            - ytcg_db_data:/var/lib/postgresql/data:rw
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready" ]
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - ytcg_internal

    adminer:
        image: adminer
        deploy:
            labels:
                - traefik.enable=true

                - traefik.http.services.ytcg_adminer.loadbalancer.server.port=8080

                - traefik.http.routers.ytcg_adminer.rule=Host(`ytcg-adminer.barlito.fr`)
                - traefik.http.routers.ytcg_adminer.entrypoints=http

                - traefik.http.routers.ytcg_adminer-secure.rule=Host(`ytcg-adminer.barlito.fr`)
                - traefik.http.routers.ytcg_adminer-secure.entrypoints=https
                - traefik.http.routers.ytcg_adminer-secure.tls=true
        networks:
            - ytcg_internal
            - traefik_traefik_proxy

volumes:
    ytcg_db_data:
    ytcg_caddy_data:

networks:
    traefik_traefik_proxy:
        external: true
    ytcg_internal:
        driver: overlay
